### ISSUE TITLE
Incorrect NaN-check

### ISSUE THREAD

**Issue by DarkWiiPlayer** [sumneko/minitable#1]
https://github.com/sumneko/minitable/blob/master/minitable.lua#L17

NaN is defined as not equal to any number, even itself; thus the only way to check whether a value `n` is NaN is by doing `n == n`. Comparing `n` to a known NaN value will still return false.

**Comment by sumneko** [comment]
This is indeed the IEEE standard, but not all platforms follow this standard. To be on the safe side, I judged both cases.

**Comment by DarkWiiPlayer** [comment]
I see, I did not consider non-standard implementations, but I guess that makes sense then.
